### ISSUE TITLE
Can I use local llm?

### ISSUE THREAD

**Issue by IcyFeather233** [zou-group/textgrad#13]
In https://github.com/zou-group/textgrad/blob/main/textgrad/engine/__init__.py, it seems that textgrad only support api model.

Is it possible to support local llm?

For example, support [OpenAI Compatible Server](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html), also accessing by api, but I can use local llm to test.

**Comment by vinid** [comment]
Hello! There are two PRs open on this, see #5 and #7 you can try to use those will we review them!

**Comment by IcyFeather233** [comment]
@vinid I tried #7  but it seems that there is some problem when using #7 in https://github.com/zou-group/textgrad/blob/main/examples/notebooks/Prompt-Optimization.ipynb

here is my code:

py file:
```
import argparse
import concurrent
from dotenv import load_dotenv
from tqdm import tqdm
import textgrad as tg
from textgrad.tasks import load_task
import numpy as np
import random
load_dotenv(override=True)

def set_seed(seed):
    np.random.seed(seed)
    random.seed(seed)
    
def eval_sample(item, eval_fn, model):
    """
    This function allows us to evaluate if an answer to a question in the prompt is a good answer.

    """
    x, y = item
    x = tg.Variable(x, requires_grad=False, role_description="query to the language model")
    y = tg.Variable(y, requires_grad=False, role_description="correct answer for the query")
    response = model(x)
    try:
        eval_output_variable = eval_fn(inputs=dict(prediction=response, ground_truth_answer=y))
        return int(eval_output_variable.value)
    except:
        eval_output_variable = eval_fn([x, y, response])
        eval_output_parsed = eval_fn.parse_output(eval_output_variable)
        return int(eval_output_parsed)
    
def eval_dataset(test_set, eval_fn, model, max_samples: int=None):
    if max_samples is None:
        max_samples = len(test_set)
    accuracy_list = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        futures = []
        for _, sample in enumerate(test_set):
            
            future = executor.submit(eval_sample, sample, eval_fn, model)
            futures.append(future)
            if len(futures) >= max_samples:
                break
        tqdm_loader = tqdm(concurrent.futures.as_completed(futures), total=len(futures), position=0)
        for future in tqdm_loader:
            acc_item = future.result()
            accuracy_list.append(acc_item)
            tqdm_loader.set_description(f"Accuracy: {np.mean(accuracy_list)}")
    return accuracy_list 

def run_validation_revert(system_prompt: tg.Variable, results, model, eval_fn, val_set):
    val_performance = np.mean(eval_dataset(val_set, eval_fn, model))
    previous_performance = np.mean(results["validation_acc"][-1])
    print("val_performance: ", val_performance)
    print("previous_performance: ", previous_performance)
    previous_prompt = results["prompt"][-1]
    
    if val_performance < previous_performance:
        print(f"rejected prompt: {system_prompt.value}")
        system_prompt.set_value(previous_prompt)
        val_performance = previous_performance

    results["validation_acc"].append(val_performance)
    
set_seed(12)

vllm_model_path = "my_path"

llm_api_eval = tg.get_engine(engine_name="vllm-qwen14b", model_string=vllm_model_path)
llm_api_test = llm_api_eval

tg.set_backward_engine(llm_api_eval, override=True)

# Load the data and the evaluation function
train_set, val_set, test_set, eval_fn = load_task("BBH_object_counting", evaluation_api=llm_api_eval)
print("Train/Val/Test Set Lengths: ", len(train_set), len(val_set), len(test_set))
STARTING_SYSTEM_PROMPT = train_set.get_task_description()

print(STARTING_SYSTEM_PROMPT)

train_loader = tg.tasks.DataLoader(train_set, batch_size=3, shuffle=True)


# Testing the 0-shot performance of the evaluation engine
system_prompt = tg.Variable(STARTING_SYSTEM_PROMPT, 
                            requires_grad=True, 
                            role_description="system prompt to the language model")
model_evaluation = tg.BlackboxLLM(llm_api_eval, system_prompt)

system_prompt = tg.Variable(STARTING_SYSTEM_PROMPT, 
                            requires_grad=True,
                            role_description="structured system prompt to a somewhat capable language model that specifies the behavior and strategies for the QA task")
model = tg.BlackboxLLM(llm_api_test, system_prompt)

optimizer = tg.TextualGradientDescent(engine=llm_api_eval, parameters=[system_prompt])

results = {"test_acc": [], "prompt": [], "validation_acc": []}
results["test_acc"].append(eval_dataset(test_set, eval_fn, model))
results["validation_acc"].append(eval_dataset(val_set, eval_fn, model))
results["prompt"].append(system_prompt.get_value())

for epoch in range(3):
    for steps, (batch_x, batch_y) in enumerate((pbar := tqdm(train_loader, position=0))):
        pbar.set_description(f"Training step {steps}. Epoch {epoch}")
        optimizer.zero_grad()
        losses = []
        for (x, y) in zip(batch_x, batch_y):
            x = tg.Variable(x, requires_grad=False, role_description="query to the language model")
            y = tg.Variable(y, requires_grad=False, role_description="correct answer for the query")
            response = model(x)
            try:
                eval_output_variable = eval_fn(inputs=dict(prediction=response, ground_truth_answer=y))
            except:
                eval_output_variable = eval_fn([x, y, response])
            losses.append(eval_output_variable)
        total_loss = tg.sum(losses)
        total_loss.backward()
        optimizer.step()
        
        run_validation_revert(system_prompt, results, model, eval_fn, val_set)
        
        print("sys prompt: ", system_prompt)
        test_acc = eval_dataset(test_set, eval_fn, model)
        results["test_acc"].append(test_acc)
        results["prompt"].append(system_prompt.get_value())
        if steps == 3:
            break
```

`textgrad/engine/vllm.py`:
```
try:
    from vllm import LLM, SamplingParams
    from transformers import AutoTokenizer
except ImportError:
    raise ImportError("If you'd like to use hugging face models, please install the vllm package by running `pip install vllm`")


import os
import platformdirs
from .base import EngineLM, CachedEngine


class ChatVllm(EngineLM, CachedEngine):
    SYSTEM_PROMPT = "You are a helpful, creative, and smart assistant."

    def __init__(
        self,
        model_string="",
        system_prompt=SYSTEM_PROMPT,
        **kwargs
    ):
        root = platformdirs.user_cache_dir("textgrad")
        cache_path = os.path.join(root, f"cache_openai_{model_string}.db")

        CachedEngine.__init__(self, cache_path=cache_path)  

        self.model_string = model_string
        self.model = LLM(model_string, **kwargs)
        self.tokenizer = AutoTokenizer.from_pretrained(model_string)
        self.system_prompt = system_prompt
        assert isinstance(self.system_prompt, str)
        EngineLM.__init__(self)


    def __call__(self, prompt, **kwargs):
        return self.generate(prompt, **kwargs)

    def generate(
        self, prompt, system_prompt=None, temperature=0, max_tokens=2000, top_p=0.99
    ):
        sampling_parameters = SamplingParams(max_tokens=max_tokens, temperature=temperature, top_p=top_p)
        sys_prompt_arg = system_prompt if system_prompt else self.system_prompt
        cache_or_none = self._check_cache(sys_prompt_arg + prompt)
        if cache_or_none is not None:
            return cache_or_none
        messages = [
                {'role': 'system', 'content': sys_prompt_arg},
                {'role': 'user', 'content': prompt}
        ]
        prompt_text = self.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        response = self.model.generate([prompt_text], sampling_params=sampling_parameters)[0].outputs[0]
        response_text = response.text
        self._save_cache(sys_prompt_arg + prompt, response_text)
        return response_text
```

`textgrad/engine/__init__.py`:
```
from .base import EngineLM, CachedEngine
from transformers import AutoConfig

__ENGINE_NAME_SHORTCUTS__ = {
    "opus": "claude-3-opus-20240229",
    "haiku": "claude-3-haiku-20240307",
    "sonnet": "claude-3-sonnet-20240229",
    "together-llama-3-70b": "together-meta-llama/Llama-3-70b-chat-hf",
}

def get_engine(engine_name: str, model_string: str, **kwargs) -> EngineLM:
    if engine_name in __ENGINE_NAME_SHORTCUTS__:
        engine_name = __ENGINE_NAME_SHORTCUTS__[engine_name]

    if "seed" in kwargs and engine_name not in ["gpt-4", "gpt-3.5"]:
        raise ValueError(f"Seed is currently supported only for OpenAI engines, not {engine_name}")

    if (("gpt-4" in engine_name) or ("gpt-3.5" in engine_name)):
        from .openai import ChatOpenAI
        return ChatOpenAI(model_string=engine_name, **kwargs)
    elif "claude" in engine_name:
        from .anthropic import ChatAnthropic
        return ChatAnthropic(model_string=engine_name, **kwargs)
    elif "gemini" in engine_name:
        from .gemini import ChatGemini
        return ChatGemini(model_string=engine_name, **kwargs)
    elif "together" in engine_name:
        from .together import ChatTogether
        engine_name = engine_name.replace("together-", "")
        return ChatTogether(model_string=engine_name, **kwargs)
    elif "vllm" in engine_name: 
        from .vllm import ChatVllm
        return ChatVllm(model_string=model_string, **kwargs)
    elif engine_name in ["command-r-plus", "command-r", "command", "command-light"]:
        from .cohere import ChatCohere
        return ChatCohere(model_string=engine_name, **kwargs)
    else:
        raise ValueError(f"Engine {engine_name} not supported")
```

and the running output:

```
You will answer a reasoning question. Think step by step. The last line of your response should be of the following format: 'Answer: $VALUE' where VALUE is a numerical value.
  0%|                                                                                                                             | 0/100 [00:00<?, ?it/s]
Processed prompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts: 100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  5.13it/s, est. speed input: 395.13 toks/s, output: 41.05 toks/s]
Processed prompts:  50%|██████████████████████                      | 1/2 [00:00<00:00, 11.39it/s, est. speed input: 1141.50 toks/s, output: 68.48 toks/s]
[rank0]: Traceback (most recent call last):                                     | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/examples/py/prompt-optimization.py", line 99, in <module>.00 toks/s, output: 0.00 toks/s]
[rank0]:     results["test_acc"].append(eval_dataset(test_set, eval_fn, model)) | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/examples/py/prompt-optimization.py", line 46, in eval_datasettoks/s, output: 0.00 toks/s]
[rank0]:     acc_item = future.result()                                         | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/concurrent/futures/_base.py", line 439, in result]
[rank0]:     return self.__get_result()                                         | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_resultssed prompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     raise self._exception                                              | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/concurrent/futures/thread.py", line 58, in runs/s]
[rank0]:     result = self.fn(*self.args, **self.kwargs)                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/examples/py/prompt-optimization.py", line 23, in eval_sample toks/s, output: 0.00 toks/s]
[rank0]:     response = model(x)                                                | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/autograd/function.py", line 80, in __call__ut: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     return self.forward(*args, **kwargs)                               | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/model.py", line 53, in forwardst. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     return self.llm_call(x)                                            | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/autograd/function.py", line 17, in __call__ut: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     return self.forward(*args, **kwargs)                               | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/autograd/llm_ops.py", line 61, in forwardnput: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     response_text = self.engine(input_variable.value, system_prompt=system_prompt_value)it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/engine/vllm.py", line 36, in __call__ed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     return self.generate(prompt, **kwargs)                             | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/textgrad/textgrad/engine/vllm.py", line 51, in generateed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     response = self.model.generate([prompt_text], sampling_params=sampling_parameters)[0].outputs[0]peed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/utils.py", line 691, in inners]
[rank0]:     return fn(*args, **kwargs)                                         | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 304, in generaterompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)                      | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 556, in _run_enginepts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     step_outputs = self.llm_engine.step()                              | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 765, in step prompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     seq_group_metadata_list, scheduler_outputs = self.scheduler.schedule()/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/core/scheduler.py", line 948, in scheduleprompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     scheduler_outputs = self._schedule()                               | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/core/scheduler.py", line 923, in _schedulerompts:   0%|                                                        | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:     return self._schedule_default()                                    | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
[rank0]:   File "/maindata/data/shared/Security-SFT/cmz/env_root/miniforge3/envs/textgrad/lib/python3.9/site-packages/vllm/core/scheduler.py", line 809, in _schedule_default   
[rank0]:     assert len(running_scheduled.prefill_seq_groups) == 0
[rank0]: AssertionError
Processed prompts:   0%|          | 0/2 [00:03<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]                                              
Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts:   0%|          | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[Program END]
```

**Comment by notV3NOM** [comment]
For openAI API compatible servers, just change the base URL
Ollama works perfectly, others should work as well

**Comment by kgourgou** [comment]
> For openAI API compatible servers, just change the base URL Ollama works perfectly, others should work as well

Exactly. For example, with an lm-studio local server. 

```python
  import os 
  os.environ['OPENAI_API_KEY'] = "lm-studio"
  os.environ['OPENAI_BASE_URL'] = "http://localhost:1234/v1"
  engine = ChatOpenAI(model_string='<your-model-name>')
  print(engine.generate(max_tokens=40, prompt="What is the meaning of life?"))
```

**Comment by HelloWorldLTY** [comment]
Hi, I tried to use local model in textgrad, however, it seems that there is a problem:
```
import textgrad as tg
import os 
from langchain_openai import ChatOpenAI
os.environ['OPENAI_API_KEY'] = "lm-studio"
os.environ['OPENAI_BASE_URL'] = "http://localhost:1234/v1"
engine = ChatOpenAI(model_string='mlabonne/NeuralBeagle14-7B-GGUF')
tg.set_backward_engine(engine, override=True)
print(engine.generate(max_tokens=40, messages="What is the meaning of life?"))
```

First, I cannot use prompt argument, and only messages work.

Second, I meet a new error:

```
TypeError: Completions.create() got an unexpected keyword argument 'model_string'
```

**Comment by kgourgou** [comment]
@HelloWorldLTY 

You need to import ChatOpenAI from `textgrad.engine`.

**Comment by HelloWorldLTY** [comment]
Hi, thanks. Now the case is a bit different. It seems that we do not use ChatOpenAI, but ChatExternalClient from textgrad.engine.local_model_openai_api. But it cannot work for me, and I will create a new issue.

**Comment by kgourgou** [comment]
So, just for the clarity of people reading this thread, when you have a local hosted model that follows the OpenAI API, you can either use 

```python 
  import os 
  os.environ['OPENAI_API_KEY'] = "lm-studio"
  os.environ['OPENAI_BASE_URL'] = "http://localhost:1234/v1"
  engine = ChatOpenAI(model_string='<your-model-name>')
  print(engine.generate(max_tokens=40, prompt="What is the meaning of life?"))
```

or just pass the client with `ChatExternalClient` (if, for example, you have custom logic in your client or you don't have access to a standard OPENAI_API_KEY). 

I'll switch to the other thread (#78 ) for your next question.

**Comment by meditans** [comment]
Thanks for the example. I think
```
from textgrad.engine import ChatOpenAI
```
should be:
```
from textgrad.engine.openai import ChatOpenAI
```
And it would be nice to have this in the documentation

**Comment by riddlegit** [comment]
My solution is make a ChatOpenAI class of own instead of digging official codes:
`
class MyChatOpenAI(ChatOpenAI):
    def __init__(
            self,
            client=None,
            **kwargs):
        super().__init__()
        self.client = client

my_client = OpenAI(base_url="http://localhost:8080/v1/")  
llm_engine = MyChatOpenAI(client=my_client)
tg.set_backward_engine(llm_engine)
...
`
